### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by juozasl** [execut/yii2-base#2]
Hi,

I have installed _execut/yii2-widget-bootstraptreeview_ and it uses _execut/yii2-base_.
I have updated all composer packages and after update get this error:

```
Class 'execut\yii\helpers\Html' not found
in /vendor/execut/yii2-base/jui/widget/Renderer.php
```

I try change file _/vendor/execut/yii2-base/jui/widget/Renderer.php_

From:

```
use execut\yii\helpers\Html;
```

To:

```
use yii\helpers\Html;
```

After this change all works fine.

**Comment by execut** [comment]
#3
